### PR TITLE
Use official bosh template test helpers

### PR DESCRIPTION
**Pull request by jamesjoshuahill**
This refactors the job template specs to use the official `Bosh::Template::Test` helpers available in the `bosh-template` gem v2.

**Note:** the fixtures use the default `spec.*` accessor values defined in the Bosh::Template::Test module, see https://bosh.io/docs/job-templates.html for a list.

### CODE REVIEW

**Comment by Benjamintf1** [comment]
@jamesjoshuahill Hello! We tried to test out the pr and are getting the failure 
```
     Failure/Error: job = release.job('syslog_forwarder')

     NameError:
       uninitialized constant Bosh::Template::Test::Job::YAML
     # /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/bosh-template-2.0.0/lib/bosh/template/test/job.rb:9:in `initialize'
     # /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/bosh-template-2.0.0/lib/bosh/template/test/release_dir.rb:8:in `new'
     # /Users/pivotal/.rvm/gems/ruby-2.4.1/gems/bosh-template-2.0.0/lib/bosh/template/test/release_dir.rb:8:in `job'
     # ./spec/syslog_forwarder_rsyslog_conf_spec.rb:7:in `block (2 levels) in <top (required)>'
```
on every test. Did you run the tests locally? Do have any idea what could be causing this?

**Comment by jamesjoshuahill** [comment]
Hi @Benjamintf1, sorry about that. I did run the tests locally, but missed this when I was deleting the old helper.

This is the Issue: https://github.com/cloudfoundry/bosh/pull/1866.

Unfortunately I don’t think there is a patch release of the bosh-template gem with the fix. So `require ‘yaml’` is needed.

**Comment by anEXPer** [comment]
Is the need for yaml temporary, then?

**Comment by jamesjoshuahill** [comment]
hi @anEXPer, so when using the `bosh-template` gem v2.0.0 you'll need the following:

```
require 'bosh/template/test'
require 'yaml'
```

Hopefully, a patch version of the `bosh-template` gem will be released that includes https://github.com/cloudfoundry/bosh/pull/1866, then the `require 'yaml'` will become superfluous.

**Comment by dpb587-pivotal** [comment]
FYI, just published [bosh-template/2.1.0](https://rubygems.org/gems/bosh-template/versions/2.1.0) which should make both of the `require "yaml"`s unnecessary.

**Pull request merged**
