### PR TITLE
Add optional syslog.migration.cleanup_conf_files property

### PR DESCRIPTION
**Pull request by alamages**
This allows bosh release authors to delete rsyslog conf files created by
other jobs or releases they have used before and avoid duplicate logs
and redundant configuration persisting in /etc/rsyslog.d/. For example, the
syslog-configurator job in cf-redis-release.

We cannot clean up these files in another bosh job because there is no
guarantee in what order pre-start scripts will be run which creates a
race condition between jobs trying to restart the rsyslog service.

[#148580247]

Signed-off-by: Emmanouil Kiagias <ekiagias@pivotal.io>

### CODE REVIEW

**Comment by jamesjoshuahill** [comment]
We considered writing the unit test in bash very briefly, but no. So we added a ruby spec in a format we are familiar with.

**Comment by scottmuc** [comment]
@jamesjoshuahill @alamages from what I can tell from your description this really is a migration only property and you would not expect to have this on the main `syslog-release`, correct?

**Comment by scottmuc** [comment]
This issue was brought up by @vlad-stoian I believe, and I think we were ok with these old files being "eventually" deleted the moment the VM was recreated.

**Comment by jamesjoshuahill** [comment]
We think that in an upgrade scenario where a job that writes a conf file to `/etc/rsyslog.d/00-my.conf` has been removed from the deployment and the `syslog_forwarder` job is added, then rsyslog will be running with the old conf file until the VM is recreated. This could cause duplicate logs until the VM is recreated.

**Comment by jamesjoshuahill** [comment]
Another alternative is to delete these files in another bosh job, but we cannot run `service rsyslog restart` because it causes a race with the restart in `syslog_forwarder`'s pre-start script.

In this scenario we cannot guarantee that rsyslog is running without the old config until the next time all the `pre-start` scripts are run.

**Comment by vlad-stoian** [comment]
I think this might also be a good thing to have in the `syslog-release` as well, since there will be scenarios where you upgrade from a pre-syslog world to a `syslog-release` world as well to a `syslog-migration-release` world.

If that's the case, I wouldn't necessarily namespace the property under `syslog.migration`.

**Comment by carlo-colombo** [comment]
Merged

**Comment by BooleanCat** [comment]
We think this is solely a migration concern. If this feature is ever needed in the main branch then it will be trivial to merge it over.

**Comment by vlad-stoian** [comment]
@BooleanCat Are you open to talking about it more before cutting a final ? I'm still not convinced this is a `syslog-migration-release` only concern.

**Pull request closed without merging**
